/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    Balloons: {
      address:
        "0x181038d01ff11089769476932f12d2ba3fc4a41efbd62d34233e8e833ac44e4",
      abi: [
        {
          type: "impl",
          name: "ERC20Impl",
          interface_name: "contracts::Balloons::IERC20",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::Balloons::IERC20",
          items: [
            {
              type: "function",
              name: "name",
              inputs: [],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "symbol",
              inputs: [],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "decimals",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "total_supply",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "balance_of",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "allowance",
              inputs: [
                {
                  name: "owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "transfer_from",
              inputs: [
                {
                  name: "sender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "approve",
              inputs: [
                {
                  name: "spender",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "BalloonsImpl",
          interface_name: "contracts::Balloons::IBalloons",
        },
        {
          type: "interface",
          name: "contracts::Balloons::IBalloons",
          items: [
            {
              type: "function",
              name: "mint",
              inputs: [
                {
                  name: "recipient",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "burn",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "recipient",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "initial_supply",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Balloons::Balloons::Transfer",
          kind: "struct",
          members: [
            {
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "value",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Balloons::Balloons::Approval",
          kind: "struct",
          members: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "spender",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "value",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Balloons::Balloons::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::Balloons::Balloons::Event",
          kind: "enum",
          variants: [
            {
              name: "Transfer",
              type: "contracts::Balloons::Balloons::Transfer",
              kind: "nested",
            },
            {
              name: "Approval",
              type: "contracts::Balloons::Balloons::Approval",
              kind: "nested",
            },
            {
              name: "OwnershipTransferred",
              type: "contracts::Balloons::Balloons::OwnershipTransferred",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x6f8cc303e5e906d1d7070c9f5333205d4d3f49180ee79f8e8c365cb1d7985d5",
    },
    DEX: {
      address:
        "0x5d63c7205aed7975cc66da472bd44bc9277b5b9a30fe7f9030a8623074933a7",
      abi: [
        {
          type: "impl",
          name: "DEXImpl",
          interface_name: "contracts::DEX::IDEX",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::DEX::IDEX",
          items: [
            {
              type: "function",
              name: "init",
              inputs: [
                {
                  name: "tokens",
                  type: "core::integer::u256",
                },
                {
                  name: "strk",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "price",
              inputs: [
                {
                  name: "input_amount",
                  type: "core::integer::u256",
                },
                {
                  name: "input_reserve",
                  type: "core::integer::u256",
                },
                {
                  name: "output_reserve",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_token_to_strk_price",
              inputs: [
                {
                  name: "token_amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_strk_to_token_price",
              inputs: [
                {
                  name: "strk_amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "strk_to_token",
              inputs: [
                {
                  name: "strk_amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "token_to_strk",
              inputs: [
                {
                  name: "tokens",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "deposit",
              inputs: [
                {
                  name: "token_amount",
                  type: "core::integer::u256",
                },
                {
                  name: "strk_amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdraw",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "(core::integer::u256, core::integer::u256)",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_total_liquidity",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_liquidity",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_token_reserve",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_strk_reserve",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "token_addr",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DEX::DEX::LiquidityProvided",
          kind: "struct",
          members: [
            {
              name: "liquidity_provider",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "liquidity_minted",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "strk_amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "token_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DEX::DEX::LiquidityRemoved",
          kind: "struct",
          members: [
            {
              name: "liquidity_provider",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "liquidity_removed",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "strk_amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "token_amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DEX::DEX::TokensSwapped",
          kind: "struct",
          members: [
            {
              name: "swapper",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "strk_input",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "token_output",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "token_input",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "strk_output",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DEX::DEX::Event",
          kind: "enum",
          variants: [
            {
              name: "LiquidityProvided",
              type: "contracts::DEX::DEX::LiquidityProvided",
              kind: "nested",
            },
            {
              name: "LiquidityRemoved",
              type: "contracts::DEX::DEX::LiquidityRemoved",
              kind: "nested",
            },
            {
              name: "TokensSwapped",
              type: "contracts::DEX::DEX::TokensSwapped",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x61ba03b2fb7f9bdc0b5f732afc3839cddb1496ef12a397fa741fec929359423",
    },
  },
} as const;

export default deployedContracts;
